POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRFU1QiLCJpZCI6IjY1YjA1MTNmMDg4NTIwOTBkYjM4ODQ5MCIsImlhdCI6MTcwNjEyNTE4NywiZXhwIjoxNzA2MTI4Nzg3fQ.5aZ6EsUHIwZRdoe-9LsqPw_V3SwWAOJZG8nU4xCbneI

{
  "title": "Test",
  "author": "Test",
  "url": "Test",
  "likes": 0,
  "user": "65b0513f08852090db388490"
}